site_name: KidPix Documentation
site_description: Documentation for the KidPix drawing application
site_author: KidPix Project
site_url: https://justinpearson.github.io/kidpix

repo_name: justinpearson/kidpix
repo_url: https://github.com/justinpearson/kidpix

docs_dir: doc
site_dir: site

nav:
  - Home: index.md
  - Philosophy: doc-philosophy.md
  - User:
      - Quick Start: user/quick-start.md
      - Use Cases: user/use-cases.md
      - How To:
          - Save Your Artwork: user/how-to/save-your-artwork.md
          - Use Wacky Brushes: user/how-to/use-wacky-brushes.md
          - View Documentation: user/how-to/view-documentation.md
  - Maintainer:
      - Quick Start: maintainer/quick-start.md
      - How To:
          - Add New Tool: maintainer/how-to/add-new-tool.md
          - Development Tasks: maintainer/how-to/development-tasks.md
          - Troubleshooting: maintainer/how-to/troubleshooting.md
          - Work with Documentation: maintainer/how-to/work-with-documentation.md
      - Explanations:
          - Architecture Overview: maintainer/explanations/architecture-overview.md
          - Technology Decisions: maintainer/explanations/technology-decisions.md
          - MkDocs Setup: maintainer/explanations/mkdocs-setup.md
          - JS to React/TS Migration:
              - Overview: maintainer/explanations/js-to-react-ts-migration/overview.md
              - Phase 1 - Foundation and Tooling: maintainer/explanations/js-to-react-ts-migration/phase-1-foundation-and-tooling.md
              - Phase 2 - TypeScript Declarations: maintainer/explanations/js-to-react-ts-migration/phase-2-add-typescript-declarations.md
              - Phase 3 - Core Architecture: maintainer/explanations/js-to-react-ts-migration/phase-3-core-architecture.md
              - Phase 4 - Tool Migration: maintainer/explanations/js-to-react-ts-migration/phase-4-tool-migration.md
              - Phase 5 - Advanced Features: maintainer/explanations/js-to-react-ts-migration/phase-5-advanced-features.md
              - Phase 6 - Polish & Optimization: maintainer/explanations/js-to-react-ts-migration/phase-6-polish-optimization.md

theme:
  name: readthedocs

markdown_extensions:
  - toc:
      permalink: true
