name: Jpp Build and Deploy App and Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Node for Vite build
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      # Python for MkDocs build
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: requirements.txt

      - run: yarn install --frozen-lockfile
      - run: pip install -r requirements.txt
      - run: pip install mkdocs
      - run: yarn build:github-pages:site # must run: Vite -> dist/, MkDocs -> dist/docs

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
