name: Build Documentation

on:
  push:
    branches: [main]
    paths:
      - "doc/**"
      - "mkdocs.yml"
      - ".github/workflows/docs.yml"
  pull_request:
    branches: [main]
    paths:
      - "doc/**"
      - "mkdocs.yml"
      - ".github/workflows/docs.yml"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install MkDocs
        run: |
          python3 -m pip install mkdocs

      - name: Build documentation
        run: mkdocs build --strict

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: site/
